name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
      uses: super-linter/super-linter@v7.2.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
