name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (npm)
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx  # Use `npx` for running ESLint without installing globally

  deploy:
    needs: linter  # Deploy only if linter passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying to development environment..."
