name: Deploy to Docker

on:
  push:
    branches:
      - dev  # Change selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Se connecter à Docker Hub
  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Build de l’image Docker
      run: docker build -t mon-utilisateur/mon-projet:latest .

    - name: Push de l’image Docker
      run: docker push mon-utilisateur/mon-projet:latest

    - name: Déploiement sur le serveur distant
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull mon-utilisateur/mon-projet:latest
          docker stop mon-container || true
          docker rm mon-container || true
          docker run -d -p 3000:3000 --name mon-container mon-utilisateur/mon-projet:latest
