<<<<<<< HEAD
name: Merge Dev to Production and Deploy

on:
  push:
    branches:
      - dev  # Se déclenche quand il y a un push sur la branche dev

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Vérifier le code du dépôt
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour effectuer un merge

      # 2️⃣ Configurer Git pour l'automatisation
      - name: Configurer Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # 3️⃣ Fusionner `dev` vers `production`
      - name: Merge dev into production
        run: |
          git checkout production
          git merge dev --no-ff -m "Automated merge from dev to production"
          git push origin production

      # 4️⃣ Déploiement après merge
      - name: Déployer l'application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé SSH stockée dans GitHub Secrets
          SERVER_USER: ${{ secrets.SERVER_USER }}  # Nom d'utilisateur SSH
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Adresse IP du serveur
          DEPLOY_PATH: "/var/www/app"  # Chemin du projet sur le serveur
        run: |
          # Ajouter la clé privée pour se connecter au serveur
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Déployer le code sur le serveur via SSH
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd $DEPLOY_PATH
            git pull origin production
            npm install --production
            pm2 restart all  # Redémarrer l'application si nécessaire
          EOF
=======
name: Prod

on:
  pull_request:
    branches:
      - prod
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install

          
      # Optionally add any post-deployment tasks
>>>>>>> 22d58602ba0c4d0bc41444f60c5ae8d176c4633b
